#ifndef __MAIN_H
#define __MAIN_H 

#include "stm32f10x.h"
#include "stm32f10x_it.h"
#include "stm32Config.h"

#define DEBUG 1

#define LEVEL_LOW 0
#define LEVEL_HIGHT 1

typedef struct
{
	int HEADER_HIGH;
	int HEADER_LOW;
	int DATA_GROUP1_MEMBER1_1;
	int DATA_GROUP1_MEMBER1_2;
	int DATA_GROUP1_MEMBER2_1;
	int DATA_GROUP1_MEMBER2_2;
	int DATA_GROUP1_MEMBER3_1;
	int DATA_GROUP1_MEMBER3_2;
	int DATA_GROUP1_MEMBER4_1;
	int DATA_GROUP1_MEMBER4_2;
	int DATA_GROUP2_MEMBER1_1;
	int DATA_GROUP2_MEMBER1_2;
	int DATA_GROUP2_MEMBER2_1;
	int DATA_GROUP2_MEMBER2_2;
	int DATA_GROUP2_MEMBER3_1;
	int DATA_GROUP2_MEMBER3_2;
	int DATA_GROUP2_MEMBER4_1;
	int DATA_GROUP2_MEMBER4_2;
	int DATA_GROUP3_MEMBER1_1;
	int DATA_GROUP3_MEMBER1_2;
	int DATA_GROUP3_MEMBER2_1;
	int DATA_GROUP3_MEMBER2_2;
	int DATA_GROUP3_MEMBER3_1;
	int DATA_GROUP3_MEMBER3_2;
	int DATA_GROUP3_MEMBER4_1;
	int DATA_GROUP3_MEMBER4_2;
} RFDataLenth_TypeDef;

enum 
{
	STATUS_HEADER_HIGH = 1,
	STATUS_HEADER_LOW,
	STATUS_GROUP1_MEMBER1_1,
	STATUS_GROUP1_MEMBER1_2,
	STATUS_GROUP1_MEMBER2_1,
	STATUS_GROUP1_MEMBER2_2,
	STATUS_GROUP1_MEMBER3_1,
	STATUS_GROUP1_MEMBER3_2,
	STATUS_GROUP1_MEMBER4_1,
	STATUS_GROUP1_MEMBER4_2,
	STATUS_GROUP2_MEMBER1_1,
	STATUS_GROUP2_MEMBER1_2,
	STATUS_GROUP2_MEMBER2_1,
	STATUS_GROUP2_MEMBER2_2,
	STATUS_GROUP2_MEMBER3_1,
	STATUS_GROUP2_MEMBER3_2,
	STATUS_GROUP2_MEMBER4_1,
	STATUS_GROUP2_MEMBER4_2,
	STATUS_GROUP3_MEMBER1_1,
	STATUS_GROUP3_MEMBER1_2,
	STATUS_GROUP3_MEMBER2_1,
	STATUS_GROUP3_MEMBER2_2,
	STATUS_GROUP3_MEMBER3_1,
	STATUS_GROUP3_MEMBER3_2,
	STATUS_GROUP3_MEMBER4_1,
	STATUS_GROUP3_MEMBER4_2
};

typedef struct
{
	int narrow_benchmark;
	int narrow_benchmark_min;
	int narrow_benchmark_max;
	int wide_benchmark;
	int wide_benchmark_min;
	int wide_benchmark_max;
} RFBenchmark_TypeDef;

#endif
